spring.application.name=Backend_Assesment


spring.datasource.url=jdbc:postgresql://localhost:5432/Assesmentdb
spring.datasource.username=${ASSESMENTDB_USERNAME}
spring.datasource.password=${ASSESMENTDB_PASSWORD}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.redis.host=localhost
spring.redis.port=6379
spring.task.scheduling.pool.size=5

